---

- name: install latest visual studio code
  community.general.snap:
    name: code
    classic: yes

- name: install some popular vscode extensions
  ansible.builtin.command: code --install-extension {{ item }}
  with_items: "{{ vscode_extensions }}"
  become: yes
  become_user: "{{ local_username }}"

...
