---

- block:
    - name: create local fonts directory
      ansible.builtin.file:
        path: "~/.local/share/fonts"
        state: directory
  become: yes
  become_user: "{{ local_username }}"

- block:
    - name: download nerd fonts to local fonts folder
      ansible.builtin.get_url:
        url: "{{ item  }}"
        dest: "~/.local/share/fonts/"
      with_items: "{{ terminal_customizations_nerd_fonts }}"
  become: yes
  become_user: "{{ local_username }}"

- name: refresh fonts cache
  ansible.builtin.shell: "fc-cache ~/.local/share/fonts/"
  become: yes
  become_user: "{{ local_username }}"

...
