---

vscode_extensions:
  - ms-vscode-remote.remote-containers
  # - aaron-bond.better-comments
  # - formulahendry.code-runner
  # - donjayamanne.githistory
  - eamodio.gitlens
  # - golang.Go
  # - vincaslt.highlight-matching-tag
  # - oderwat.indent-rainbow
  # - yzhang.markdown-all-in-one
  # - ms-python.python
  # - ms-python.vscode-pylance
  # - humao.rest-client
  - Gruntfuggly.todo-tree
  # - shardulm94.trailing-spaces
  - dracula-theme.theme-dracula
  - PKief.material-icon-theme
  # - Equinusocio.vsc-material-theme
  - vscodevim.vim
  - visualstudioexptteam.vscodeintellicode
  - ms-azuretools.vscode-docker
  # - vscode-icons-team.vscode-icons
  # - esbenp.prettier-vscode
  # - redhat.vscode-yaml
  # - danielroedl.meld-diff
  # - davidanson.vscode-markdownlint
  # - hashicorp.terraform

...
