---

- name: install vim apt packages
  ansible.builtin.apt:
    name: "{{ vim_apt_packages }}"
    state: present
    force_apt_get: yes

- name: Set default text editor to vim
  community.general.alternatives:
    name: editor
    path: /usr/bin/vim.basic

- name: Install Vundle (plugin manager)
  ansible.builtin.git:
    repo: 'https://github.com/VundleVim/Vundle.vim.git'
    dest: ~/.vim/bundle/Vundle.vim
  become: true
  become_user: "{{ local_username }}"


- name: add custom vim config
  ansible.builtin.copy:
    src: .vimrc
    dest: "~{{ local_username }}/.vimrc"
    mode: '0644'
    force: yes
    backup: yes

  become: true
  become_user: "{{ local_username }}"

- name: Install Vim plugins
  ansible.builtin.shell: vim -c ':PluginInstall' -c ':qa'

...
